name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r2n9m4w8
      - name: Build docker image
        run: docker build -t public.ecr.aws/r2n9m4w8/playpal_event_service:latest -f backend/eventCreation/Dockerfile backend/eventCreation
      - name: Publish image to docker hub
        run: docker push public.ecr.aws/r2n9m4w8/playpal_event_service:latest

  build-ml:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r2n9m4w8
      - name: Build docker image
        run: docker build -t public.ecr.aws/r2n9m4w8/playpal_ml_repo:latest -f backend/mlService/Dockerfile backend/mlService
      - name: Publish image to docker hub
        run: docker push public.ecr.aws/r2n9m4w8/playpal_ml_repo:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull public.ecr.aws/r2n9m4w8/playpal_event_service:latest
      - name: Delete old container
        run: docker rm -f playpal
      - name: Run docker container
        run: docker run -d -p 3500:3500 --name playpal public.ecr.aws/r2n9m4w8/playpal_event_service:latest

  deploy-ml:
    needs: build-ml
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull public.ecr.aws/r2n9m4w8/playpal_ml_repo:latest
      - name: Delete old container
        run: docker rm -f playpal-ml
      - name: Run docker container
        run: docker run -d -p 3501:3501 --name playpal-ml public.ecr.aws/r2n9m4w8/playpal_ml_repo:latest
