name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ashishvedasjsu/playpal -f backend/eventCreation/Dockerfile backend/eventCreation
      - name: Publish image to docker hub
        run: docker push ashishvedasjsu/playpal:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ashishvedasjsu/playpal:latest
      - name: Delete old container
        run: docker rm -f playpal
      - name: Run docker container
        run: docker run -d -p 3500:3500 --name playpal ashishvedasjsu/playpal
